// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rghakqvaawoopcoeowir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnaGFrcXZhYXdvb3Bjb2Vvd2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODM1MTUsImV4cCI6MjA1Njg1OTUxNX0.qJctyimvaBcSy3QJ0bWMSaDom1EK6g39wz-7i6Ris0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);