// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncyvwfsxpkxbmbismuhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jeXZ3ZnN4cGt4Ym1iaXNtdWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NzM4MTEsImV4cCI6MjA4MTA0OTgxMX0.DfLeuVZuIUTjBz5wcq5Ch26JrjfXeCeTJJ8PepBp3B0";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
  },
});
